/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyChildComponentTwo {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyComponentTwo {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMyChildComponentTwoElement extends Components.MyChildComponentTwo, HTMLStencilElement {
    }
    var HTMLMyChildComponentTwoElement: {
        prototype: HTMLMyChildComponentTwoElement;
        new (): HTMLMyChildComponentTwoElement;
    };
    interface HTMLMyComponentTwoElement extends Components.MyComponentTwo, HTMLStencilElement {
    }
    var HTMLMyComponentTwoElement: {
        prototype: HTMLMyComponentTwoElement;
        new (): HTMLMyComponentTwoElement;
    };
    interface HTMLElementTagNameMap {
        "my-child-component-two": HTMLMyChildComponentTwoElement;
        "my-component-two": HTMLMyComponentTwoElement;
    }
}
declare namespace LocalJSX {
    interface MyChildComponentTwo {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyComponentTwo {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-child-component-two": MyChildComponentTwo;
        "my-component-two": MyComponentTwo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-child-component-two": LocalJSX.MyChildComponentTwo & JSXBase.HTMLAttributes<HTMLMyChildComponentTwoElement>;
            "my-component-two": LocalJSX.MyComponentTwo & JSXBase.HTMLAttributes<HTMLMyComponentTwoElement>;
        }
    }
}
